"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { useEffect } from "react";
import { User, useUserStore } from "@/store/user.store";
import { todoActions, userActions } from "@/actions";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// socket connection

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const socket = new WebSocket("ws://localhost:3003");
    socket.onopen = () => {
      console.log("WebSocket is connected");
    };
    socket.onmessage = (message) => {
      console.log("Message: ", message);
    };

    // Clean up the connection when the component is unmounted
    return () => {
      socket.close();
    };
  }, []);

  const { setUser } = useUserStore();
  useEffect(() => {
    const id = localStorage.getItem("id");
    (async () => {
      const userData = await userActions.FetchUser();

      const users = userData.data.filter((item: any) => item._id === id);
      console.log(users[0], "----");

      const mappedData: User = {
        id: users[0]._id,
        username: users[0].username,
        email: users[0].email,
        isAuthenticated: true,
        created_at: users[0].createdAt,
        updated_at: users[0].updatedAt,
      };

      setUser(mappedData);
    })();
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
          {/* <Navbar /> */}
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
